import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');
const mono = Platform.OS === 'ios' ? 'Menlo' : 'monospace';

export const styles = StyleSheet.create({
  // Layout
  container: { flex: 1, backgroundColor: '#0f0f23' },
  scrollView: { flex: 1, paddingHorizontal: 20 },

  // Header
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 20 },
  greeting: { fontSize: 14, color: '#94a3b8', fontWeight: '500' },
  appTitle: { fontSize: 28, fontWeight: '700', color: '#fff' },
  notifButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#252547', justifyContent: 'center', alignItems: 'center' },
  notifIcon: { fontSize: 20 },

  // Hydration
  hydrationCard: { backgroundColor: '#1e3a5f', borderRadius: 24, padding: 20, marginBottom: 20, borderWidth: 2, borderColor: '#3b82f6' },
  hydrationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  hydrationTitle: { fontSize: 20, fontWeight: '700', color: '#fff' },
  hydrationSubtitle: { fontSize: 14, color: '#93c5fd', fontWeight: '600' },
  progressContainer: { marginBottom: 20 },
  progressBar: { height: 12, backgroundColor: 'rgba(59,130,246,0.2)', borderRadius: 6, overflow: 'hidden', marginBottom: 8 },
  progressFill: { height: '100%', backgroundColor: '#3b82f6', borderRadius: 6 },
  progressText: { fontSize: 14, color: '#93c5fd', textAlign: 'center', fontWeight: '600', fontFamily: mono },
  glassCounter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  glassBtn: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(59,130,246,0.2)', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#3b82f6' },
  glassBtnAdd: { backgroundColor: '#3b82f6' },
  glassBtnText: { fontSize: 28, fontWeight: '700', color: '#3b82f6' },
  glassBtnAddText: { color: '#fff' },
  glassDisplay: { alignItems: 'center', paddingHorizontal: 24 },
  glassCount: { fontSize: 48, fontWeight: '700', color: '#fff', fontFamily: mono },
  glassLabel: { fontSize: 14, color: '#93c5fd', marginTop: -4 },
  quickAddRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, marginBottom: 12 },
  quickAddBtn: { flex: 1, backgroundColor: 'rgba(59,130,246,0.2)', paddingVertical: 12, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(59,130,246,0.3)' },
  quickAddText: { fontSize: 13, fontWeight: '600', color: '#93c5fd' },
  hydrationStatus: { backgroundColor: 'rgba(59,130,246,0.1)', borderRadius: 12, padding: 12 },
  hydrationStatusText: { fontSize: 13, color: '#93c5fd', textAlign: 'center', fontWeight: '500' },

  // Workout Shift Toggle
  shiftToggleContainer: { marginBottom: 16 },
  shiftToggleLabel: { fontSize: 12, fontWeight: '600', color: '#94a3b8', letterSpacing: 1, marginBottom: 8 },
  shiftToggleRow: { flexDirection: 'row', gap: 12 },
  shiftToggleButton: { flex: 1, backgroundColor: '#252547', borderRadius: 14, paddingVertical: 14, paddingHorizontal: 16, alignItems: 'center', borderWidth: 2, borderColor: 'rgba(255,255,255,0.08)' },
  shiftToggleActive: { backgroundColor: 'rgba(124,58,237,0.25)', borderColor: '#7c3aed' },
  shiftToggleText: { fontSize: 15, fontWeight: '600', color: '#64748b' },
  shiftToggleTextActive: { color: '#c4b5fd' },

  // Today Workout
  todayCard: { backgroundColor: '#7c3aed', borderRadius: 24, padding: 24, marginBottom: 24 },
  restCard: { backgroundColor: '#374151' },
  todayLabel: { fontSize: 12, fontWeight: '600', color: 'rgba(255,255,255,0.8)', letterSpacing: 1, marginBottom: 8 },
  todayWorkout: { fontSize: 24, fontWeight: '700', color: '#fff', marginBottom: 16 },
  exerciseTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  exerciseTag: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  exerciseTagText: { fontSize: 12, fontWeight: '500', color: '#fff' },
  startButton: { backgroundColor: 'rgba(255,255,255,0.95)', borderRadius: 16, padding: 16, alignItems: 'center' },
  startButtonText: { fontSize: 16, fontWeight: '700', color: '#7c3aed' },

  // Followup
  followupCard: { backgroundColor: '#252547', borderRadius: 24, padding: 24, marginBottom: 24, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  followupTitle: { fontSize: 18, fontWeight: '600', color: '#fff', textAlign: 'center', marginBottom: 20 },
  followupButtons: { flexDirection: 'row', gap: 12 },
  followupBtn: { flex: 1, padding: 16, borderRadius: 16, alignItems: 'center', borderWidth: 2 },
  yesBtn: { backgroundColor: 'rgba(16,185,129,0.15)', borderColor: '#10b981' },
  yesBtnText: { fontSize: 15, fontWeight: '600', color: '#10b981' },
  noBtn: { backgroundColor: 'rgba(239,68,68,0.15)', borderColor: '#ef4444' },
  noBtnText: { fontSize: 15, fontWeight: '600', color: '#ef4444' },

  // Section Title
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#fff', marginBottom: 16 },

  // Week Grid
  weekGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 28 },
  dayCard: { width: (width - 56) / 7, backgroundColor: '#252547', borderRadius: 12, padding: 8, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  todayDayCard: { borderColor: '#7c3aed', backgroundColor: 'rgba(124,58,237,0.2)' },
  completedDayCard: { backgroundColor: 'rgba(16,185,129,0.15)', borderColor: '#10b981' },
  restDayCard: { opacity: 0.5 },
  dayName: { fontSize: 10, fontWeight: '600', color: '#94a3b8', textTransform: 'uppercase' },
  dayNum: { fontSize: 16, fontWeight: '700', color: '#fff', marginVertical: 4 },
  dayType: { backgroundColor: 'rgba(124,58,237,0.3)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  restDayType: { backgroundColor: 'rgba(100,116,139,0.3)' },
  completedDayType: { backgroundColor: 'rgba(16,185,129,0.3)' },
  dayTypeText: { fontSize: 7, fontWeight: '600', color: '#c4b5fd', textTransform: 'uppercase' },
  restDayTypeText: { color: '#64748b' },
  completedDayTypeText: { color: '#6ee7b7' },
  checkIcon: { fontSize: 12, color: '#10b981', marginTop: 4 },

  // Rest Day Banner
  restDayBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(100,116,139,0.15)', borderRadius: 16, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(100,116,139,0.3)' },
  restDayBannerIcon: { fontSize: 28, marginRight: 12 },
  restDayBannerContent: { flex: 1 },
  restDayBannerTitle: { fontSize: 14, fontWeight: '700', color: '#cbd5e1', marginBottom: 2 },
  restDayBannerText: { fontSize: 11, color: '#94a3b8', lineHeight: 16 },

  // Reminders
  remindersSection: { marginBottom: 28 },
  reminderCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#252547', borderRadius: 20, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  hydrationReminderCard: { borderColor: '#3b82f6', backgroundColor: 'rgba(30,58,95,0.5)' },
  reminderIcon: { width: 48, height: 48, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  reminderIconText: { fontSize: 22 },
  reminderContent: { flex: 1 },
  reminderTitle: { fontSize: 16, fontWeight: '600', color: '#fff', marginBottom: 4 },
  reminderTime: { fontSize: 13, color: '#94a3b8', fontFamily: mono },
  alwaysOnBadge: { backgroundColor: '#3b82f6', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  alwaysOnText: { fontSize: 10, fontWeight: '700', color: '#fff', letterSpacing: 0.5 },
  reminderCardCompleted: { opacity: 0.65, borderColor: '#10b981', backgroundColor: 'rgba(16,185,129,0.08)' },
  reminderPressArea: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  completionCircle: { width: 28, height: 28, borderRadius: 14, borderWidth: 2, borderColor: '#475569', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  completionCircleDone: { backgroundColor: '#10b981', borderColor: '#10b981' },
  completionCheck: { fontSize: 14, color: '#fff', fontWeight: '700' },
  reminderTitleCompleted: { textDecorationLine: 'line-through', color: '#64748b' },
  reminderTimeAdjusted: { color: '#f59e0b' },
  reminderDoneAt: { fontSize: 11, color: '#10b981', fontWeight: '600' },
  reminderMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  reminderTap: { fontSize: 11, color: '#64748b', fontStyle: 'italic' },

  // Modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#1a1a2e', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, paddingBottom: 40, maxHeight: '85%' },
  modalHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  modalIconBadge: { width: 56, height: 56, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  modalIcon: { fontSize: 28 },
  modalHeaderText: { flex: 1 },
  modalTitle: { fontSize: 20, fontWeight: '700', color: '#fff', marginBottom: 4 },
  modalTime: { fontSize: 14, color: '#94a3b8', fontFamily: mono },
  modalDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.08)', marginBottom: 20 },
  modalSectionLabel: { fontSize: 11, fontWeight: '700', color: '#94a3b8', letterSpacing: 1.5, marginBottom: 12, marginTop: 8 },
  modalItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10, paddingLeft: 4 },
  modalBullet: { fontSize: 15, color: '#7c3aed', fontWeight: '700', marginRight: 10, width: 18 },
  modalItemText: { fontSize: 15, color: '#e2e8f0', flex: 1, lineHeight: 22 },
  modalTipBox: { backgroundColor: 'rgba(124,58,237,0.12)', borderRadius: 14, padding: 14, marginTop: 16, marginBottom: 8, borderWidth: 1, borderColor: 'rgba(124,58,237,0.25)' },
  modalTipLabel: { fontSize: 11, fontWeight: '700', color: '#a78bfa', letterSpacing: 1, marginBottom: 6 },
  modalTipText: { fontSize: 13, color: '#c4b5fd', lineHeight: 20 },
  modalCompleteBtn: { backgroundColor: '#10b981', borderRadius: 16, padding: 16, alignItems: 'center', marginTop: 20 },
  modalCompleteBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },
  modalCompletedBadge: { backgroundColor: 'rgba(16,185,129,0.15)', borderRadius: 14, padding: 14, alignItems: 'center', marginTop: 20, borderWidth: 1, borderColor: '#10b981' },
  modalCompletedText: { fontSize: 14, fontWeight: '600', color: '#10b981' },
  modalCompletedMeal: { fontSize: 12, color: '#94a3b8', marginTop: 6, textAlign: 'center' },
  modalMacroRow: { flexDirection: 'row', justifyContent: 'center', gap: 8, marginTop: 8 },
  modalMacroChip: { fontSize: 12, fontWeight: '700', fontFamily: mono },
  modalCloseBtn: { backgroundColor: '#252547', borderRadius: 16, padding: 16, alignItems: 'center', marginTop: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  modalCloseBtnText: { fontSize: 16, fontWeight: '700', color: '#94a3b8' },

  // Meal Picker
  mealPickerSubtitle: { fontSize: 13, color: '#94a3b8', marginBottom: 12 },
  mealPickerScroll: { maxHeight: 400 },
  mealOptionCard: { backgroundColor: '#252547', borderRadius: 14, padding: 16, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  mealOptionLabel: { fontSize: 14, fontWeight: '600', color: '#e2e8f0', marginBottom: 8 },
  mealOptionMacros: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  macroChip: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  macroChipText: { fontSize: 11, fontWeight: '700', fontFamily: mono },
  customMealSection: { marginBottom: 16, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  customMealLabel: { fontSize: 12, fontWeight: '600', color: '#94a3b8', marginBottom: 8 },
  customMealInput: { backgroundColor: '#252547', borderRadius: 12, padding: 14, color: '#fff', fontSize: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', marginBottom: 10 },
  customMealRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  customMealField: { flex: 1, backgroundColor: '#252547', borderRadius: 10, padding: 12, color: '#fff', fontSize: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  customMealBtn: { backgroundColor: '#7c3aed', borderRadius: 12, padding: 14, alignItems: 'center', marginTop: 4 },
  customMealBtnText: { fontSize: 14, fontWeight: '600', color: '#fff' },

  // Macro Tracker
  macroTrackerCard: { backgroundColor: '#252547', borderRadius: 24, padding: 20, marginBottom: 28, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  macroCalorieHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center', marginBottom: 12 },
  macroCalorieValue: { fontSize: 36, fontWeight: '700', color: '#f97316', fontFamily: mono },
  macroCalorieLabel: { fontSize: 14, color: '#94a3b8', marginLeft: 6, fontWeight: '600' },
  macroProgressBar: { height: 8, backgroundColor: 'rgba(249,115,22,0.15)', borderRadius: 4, overflow: 'hidden', marginBottom: 20 },
  macroProgressFill: { height: '100%', borderRadius: 4 },
  macroBreakdown: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 16 },
  macroColumn: { alignItems: 'center', flex: 1 },
  macroValue: { fontSize: 20, fontWeight: '700', fontFamily: mono, marginBottom: 6 },
  macroMiniBar: { height: 6, width: '80%', backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 3, overflow: 'hidden', marginBottom: 4 },
  macroMiniFill: { height: '100%', borderRadius: 3 },
  macroGoalText: { fontSize: 10, color: '#64748b', fontFamily: mono, marginBottom: 2 },
  macroLabel: { fontSize: 11, color: '#94a3b8', fontWeight: '600' },
  macroMealsLog: { borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.06)', paddingTop: 14 },
  macroMealsTitle: { fontSize: 10, fontWeight: '700', color: '#64748b', letterSpacing: 1.5, marginBottom: 10 },
  macroMealRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  macroMealTime: { fontSize: 11, color: '#64748b', fontFamily: mono, width: 65 },
  macroMealLabel: { fontSize: 12, color: '#cbd5e1', flex: 1 },
  macroMealCal: { fontSize: 12, fontWeight: '700', color: '#f97316', fontFamily: mono },

  // Stats
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 28 },
  statCard: { width: (width - 52) / 2, backgroundColor: '#252547', borderRadius: 20, padding: 20, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  statValue: { fontSize: 32, fontWeight: '700', marginBottom: 4, fontFamily: mono },
  statLabel: { fontSize: 12, color: '#94a3b8', fontWeight: '500' },

  // Toggle (unused in current UI but kept for reminder toggles)
  toggle: { width: 52, height: 32, borderRadius: 16, backgroundColor: 'rgba(100,116,139,0.3)', padding: 3 },
  toggleEnabled: { backgroundColor: '#10b981' },
  toggleKnob: { width: 26, height: 26, borderRadius: 13, backgroundColor: '#fff' },
  toggleKnobEnabled: { transform: [{ translateX: 20 }] },
});
